export const IpcChannels = {
  AppGetVersion: 'app:get-version',
  AppQuit: 'app:quit',
  AppMoveWindow: 'app:move-window',
  AppShowContextMenu: 'app:show-context-menu',
  PetSetState: 'pet:set-state',
  ChatGetHistory: 'chat:get-history',
  ChatSendMessage: 'chat:send-message',
  TodoCreate: 'todo:create',
  TodoList: 'todo:list',
  TodoComplete: 'todo:complete',
  TodoDelete: 'todo:delete',
  ReminderList: 'reminder:list',
  ReminderSnooze: 'reminder:snooze',
  AgentGetStatus: 'agent:get-status',
  AgentGetHistory: 'agent:get-history',
  AgentHookDiscover: 'agent-hook:discover',
  AgentHookGetStatus: 'agent-hook:get-status',
  AgentHookInstallClaude: 'agent-hook:install-claude',
  AgentHookRemoveClaude: 'agent-hook:remove-claude',
  AgentHookInstallClaudeProject: 'agent-hook:install-claude-project',
  AgentHookRemoveClaudeProject: 'agent-hook:remove-claude-project',
  AgentTaskCreate: 'agent-task:create',
  AgentTaskUpdateStatus: 'agent-task:update-status',
  AgentTaskDelete: 'agent-task:delete',
  MemoryList: 'memory:list',
  MemoryCreate: 'memory:create',
  MemoryDelete: 'memory:delete',
  SharePreview: 'share:preview',
  ShareGenerate: 'share:generate',
  SettingsGetDeepSeekConfig: 'settings:get-deepseek-config',
  SettingsUpdateDeepSeekConfig: 'settings:update-deepseek-config',
  SettingsGetDataLocation: 'settings:get-data-location',
  SettingsOpenDataLocation: 'settings:open-data-location',
  SettingsClearChatHistory: 'settings:clear-chat-history',
  SettingsClearMemories: 'settings:clear-memories',
  SettingsGetPetConfig: 'settings:get-pet-config',
  SettingsUpdatePetConfig: 'settings:update-pet-config',
  SettingsGetNotificationConfig: 'settings:get-notification-config',
  SettingsUpdateNotificationConfig: 'settings:update-notification-config'
} as const;

export type IpcChannel = (typeof IpcChannels)[keyof typeof IpcChannels];
